version: "3.7"
services:
  db:
    image: postgres:15.3-alpine3.18
    container_name: db_app_tg
    command: -p 5535
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5535
    env_file:
      - .env

  telegram_bot_prozorro:
    build:
      context: .
    env_file:
      - .env
    container_name: telegram_bot_prozorro
    command: ["/telegram_bot_prozorro/docker/run_bot.sh"]
    depends_on:
      - db
    environment:
      - TZ=Europe/Kiev

volumes:
  pgdata:
