"""initial

Revision ID: b2934d020b63
Revises: 
Create Date: 2023-12-17 20:45:33.321949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2934d020b63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('DK021_2015', sa.String(), nullable=False),
    sa.Column('Status', sa.String(), nullable=False),
    sa.Column('Procurement_type', sa.String(), nullable=False),
    sa.Column('Region', sa.String(), nullable=False),
    sa.Column('Dispatch_time', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings_table')
    # ### end Alembic commands ###
